#!/bin/bash
set -e

# Ensure wasm-pack is installed
if ! command -v wasm-pack &>/dev/null; then
  echo "Error: wasm-pack is not installed"
  echo "Please install wasm-pack: cargo install wasm-pack"
  exit 1
fi

# Build directory setup
WASM_OUT_DIR="wasm-tests/pkg"
mkdir -p "$WASM_OUT_DIR"

echo "Building samod WASM package..."

# Build the WASM package with the wasm feature enabled
cd samod
wasm-pack build \
  --target web \
  --out-dir "../$WASM_OUT_DIR" \
  --features wasm \
  --no-default-features

cd ..

echo "WASM build complete! Output in $WASM_OUT_DIR"

# Generate TypeScript types if requested
if [[ "$3" == "--typescript" ]]; then
  echo "Generating TypeScript definitions..."
  # The TypeScript definitions are automatically generated by wasm-pack
  echo "TypeScript definitions generated in $WASM_OUT_DIR"
fi

